image: maven:3.6.3-jdk-8

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  when: manual
  allow_failure: false
  script:
    - mvn install -Dmaven.test.skip=true -B
  artifacts:
    paths:
      - target/weatherPredictionService-0.0.1-SNAPSHOT.jar

deploy_dev:
  image: python:latest
  stage: deploy
  only:
    - development
  when: on_success
  script:
    - echo "Deploy to dev server 1"
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region us-east-1
    - aws s3 cp target/weatherPredictionService-0.0.1-SNAPSHOT.jar elasticbeanstalk-us-east-1-767618353923/gitlab-cicd/weather-prediction-be/weatherPredictionServiceGitlabCICD-dev-$CI_PIPELINE_ID.jar
    - aws elasticbeanstalk create-application-version --application-name PublicSapient --version-label weatherPredictionServiceGitlabCICD-dev-$CI_PIPELINE_ID --source-bundle S3Bucket=elasticbeanstalk-us-east-1-767618353923,S3Key=gitlab-cicd/weather-prediction-be/weatherPredictionServiceGitlabCICD-dev-$CI_PIPELINE_ID.jar
    - aws elasticbeanstalk update-environment --application-name PublicSapient --environment-name Publicsapient-env-2 --version-label weatherPredictionServiceGitlabCICD-dev-$CI_PIPELINE_ID
  dependencies:
    - build
